### PR TITLE
Zeus support

### PR DESCRIPTION
**Pull request by mikeNG**
Initial changes for supporting zeus board

### CODE REVIEW

**Comment by mikeNG** [comment]
Pull request opened for reference & development only
WIP, untested on device.

Remaining source to port:
-Everything Wifi & BT related
-Touchpads

**Comment by lukasreuter** [comment]
Tested on device zeus R800i and is unfortunately not booting, the phone vibrates on pressing the power button but does not turn on the display and doesn't seem to load anything. Would supply dmesg but honestly i don't know how to obtain the log in this special case. Tried with with ramdisk from fxp cm10 kernel and pac rom 6.1 by wedgess (android 4.1.2).

**Comment by adrientetar** [comment]
@Luxxuor hotboot the faulty kernel then boot back to 2.6.32 and see if you have a last_kmsg.

I don't know how early the kernel logging starts through.

**Comment by lukasreuter** [comment]
@adridu59 Finally got around to try it, but no dice. I tried it in two ways: after booting back into recovery of 2.6.32 i used adb shell to retrieve proc/last_kmsg but it was not existing, then i tried booting back into system after hotbooting and retrieve it via terminal but it didn't exist either. So it is pretty clear the problem seems to be before the logging even starts.

**Comment by mikeNG** [comment]
I think that without UART debugging it's going to be hard to make it work

**Comment by lukasreuter** [comment]
Which is unfortunately to advanced for me, maybe we should get other zeus/phoenix owners like doomlord or nickholtus involved.

**Comment by M66B** [comment]
Speaking of which, given the amount of work do for CM10.1 and kernel 3.4 it would we a good idea to unite all developers.

**Comment by DooMLoRD** [comment]
@M66B i am already working on the 3.4 kernel for zeus... right now lots of preliminary patching going on for board file..

**Comment by M66B** [comment]
@DooMLoRD what I mean is that everybody seems to have own repo's and I frequently see that people copy each other work (nothing bad with that in itself). This is inefficient and IMHO we should have common repo's, common documentation, common issue tracker, etc. In other works, make CM10.1 / kernel 3.4 a common project.

**Comment by DooMLoRD** [comment]
Well we did try to start it but some people are hell bent on using their
own sources... Mind you I am Not pointing fingers at anyone...

May be we cam have CM-gerrit type code review system?

**Comment by adrientetar** [comment]
Proper use of git would require proper commits (one commit for one feature) and not kanging work of others -- I do not really care about that one personally but some might.
Or maybe it's just a matter of commit tree (the order in which things are done), who knows.

**Pull request closed without merging**
