### PR TITLE
irii

### PR DESCRIPTION
**Pull request by irii**

### CODE REVIEW

**Comment by nobodyAtall** [comment]
Can you please rebase on latest merge? Also remove 5e4c560, it's not needed.

Thanks.

**Comment by irii** [comment]
Im not a good git expert I'm just a coder :) What I need to do for rebase?

**Comment by mikeNG** [comment]
These:
64f6c5d52989a7b9369ac9c21cbd275d4a2188e7
d842d32a1ed7b21d047804fe0340e39e5dc298c9
are not needed too, they were merged in mechmetal's haida pull request

Edit: http://git-scm.com/book/en/Git-Branching-Rebasing

**Comment by nobodyAtall** [comment]
d842d32 is needed. It adds the missing drivers/video/msm/mddi_nt_panels panels

64f6c5d fixes drivers/input/misc/bma150_ng.c. I'm not sure if the board file change was necessary (moving the structs upwards)...

**Comment by nobodyAtall** [comment]
@irii-soft Please sync with latest fixes and do what's needed (only that) for making urushi work. Separate these also in small bite-able chunks so we can review the code. 

Thanks.

**Comment by mikeNG** [comment]
@nobodyAtall weren't the panels merged here 8d7dd4a31d44b86fee3521b3f617fe768df460b9 ?

Edit: the bma_150 fix was merged here too 69b6d6e4c39bf1f900f827b690b8af3196b8b41f

Anyway, irii just needs to rebase and find what's needed now.

**Comment by nobodyAtall** [comment]
You are correct :)

**Comment by irii** [comment]
Ok will do it :)
Next thing what I started to do and what we should do is to remove unnecessary code from the mogami board for example surf, ffa, ...

**Pull request closed without merging**
