### PR TITLE
leds: hardcode max_current

### PR DESCRIPTION
**Pull request by mikeNG**
Instead of relying to scripts that might be not present in different ramdisks to set the max_current at boot time, hardcode the values in the drivers like it was done for zeus board

The values come from stock rom's pre_hw_config.sh & hw_config.sh

Change-Id: Ia92a0b0193803fefb3f32569e0414604855c64e9
Signed-off-by: Michael Bestas mikeioannina@gmail.com

### CODE REVIEW

**Comment by CTCaer** [comment]
Many people want brighter leds. May I propose something like a change in line 1342 in /drivers/leds/leds-as3676.c:
if (curr_val > pdata->leds[intf->index].max_current)
to
if (curr_val > pdata->leds[intf->index].hw_max_current)
so it checks .hw_max_current at arch/arm/mach-msm/leds-*.c, 
and adding 
intf->hw_max_current = led->hw_max_current;
near after line 1682 and finally adding hw_max_current to leds-as3676.h?

So in the end they will have the stock values from scripts, but also they can be brighter if wanted without risking burning them.

**Comment by mikeNG** [comment]
I think that people can still change the max_current to a higher value in scripts, I will test that and tell you

**Comment by CTCaer** [comment]
Well the driver keeps an index with all original values. 
As I understand from the one below (line1342@leds-as3676.c, storing values through sysfs):

as

It checks the new value with the one specified in leds-*.c (leds[intf->index]). That means if we enter a bigger value it will remain the same as I commented in the above image. You can try it anyway. It's the same with any value.
For example echo "300" to brightness and it will default to it's max: 255. 

For max_current it's mostly a mechanism to protect the leds from burning.
AS3676 can output a max 38.25mA to any output. If for example you make the max_current in Urushi from 20000 to 38250 you gonna fry the leds or decrease their life by a big margin.

If you don't have time, I can come up with a patch for this when possible.

**Comment by mikeNG** [comment]
I don't have time to do this but I want to hear @nobodyAtall 's opinion on this.

**Comment by adrientetar** [comment]
@CTCaer have a patch to upload?

**Comment by CTCaer** [comment]
Not yet. I'll work on it today

**Comment by nobodyAtall** [comment]
Words like 'fry' or 'shorten life' don't sound good. I don't understand why do we need to change this?
Isn't userspace control enough?

**Comment by mikeNG** [comment]
The max current was set from pre_hw_config.sh on stock roms.
pre_hw_config.sh was not executed on all ics & jb CM roms since there were changes for recovery and later 2 stage boot. Nobody had noticed that until I saw this one month ago.

I think my commit is useful for these circumstances: indication for recovery (notification, keyboard & backlight leds) as well as max_current inside recovery. The leds will operate with safe current and users won't risk frying them.

It seems scary to me to use the leds with their current max_current, check the difference between the values and you'll see what I mean. Operating leds at 25mA while they were supposed to use 0.9mA seems not safe at all to me.

**Comment by CTCaer** [comment]
These words were just mentioned by me to tell what's the purpose of having max_current at leds-*.c.
The 25mA and 20mA are absolutely safe.
The reasons that OEMs use other values are for having:
1. A little less drain from leds.
2. Not too much bright leds. So they don't annoy some.
3. Some leds are brighter than the other, so different values must be set to have a real RGB effect.

Still there are users that want brighter leds.

So, I'm all in for  mikeNG's patch, so rom builders don't have to add scripts for stock values.
And I'll work on a patch that can let users change the leds to higher values, that can't be higher than max safe (original)  values.

EDIT:
Also about leds, most leds out there are made to work on 20mA for 100.000 hours. There are some that work on higher values. So as I just said working on 20mA-25mA is absolutely safe.
Commit 0bb5d91 must be considered a good patch anyway.

**Comment by CTCaer** [comment]
Here's the patch for letting again users reach leds' max safe current and still maintain the above commit's hardcoded values.
https://github.com/CTCaer/msm7x30-3.0.x-nAa/commit/5649c209a97781ab996585bb3ddb530a76a86826.patch

**Comment by adrientetar** [comment]
@CTCaer @nobodyAtall Looks good to me.

**Comment by mikeNG** [comment]
Looks good to me too.

**Comment by mikeNG** [comment]
Closing this, forgot to branch before pushing

**Pull request closed without merging**
