### PR TITLE
Backport ROW scheduler from CAF 3.4

### PR DESCRIPTION
**Pull request by mikeNG**
The ROW scheduling algorithm will be used in mobile devices as default
block layer IO scheduling algorithm. ROW stands for "READ Over WRITE"
which is the main requests dispatch policy of this algorithm.

The ROW IO scheduler was developed with the mobile devices needs in
mind. In mobile devices we favor user experience upon everything else,
thus we want to give READ IO requests as much priority as possible.
The main idea of the ROW scheduling policy is:
If there are READ requests in pipe - dispatch them but don't starve
the WRITE requests too much.

### CODE REVIEW

**Comment by mikeNG** [comment]
Currently untested but compiles without errors. I'll test in a few hours

**Comment by mikeNG** [comment]
Tested & working on smultron, although I don't know how to test the difference between other schedulers and ROW. It's supposed to be better than the other schedulers because it's designed with mobile devices in mind, many official CM devices have this merged & use it as default scheduler

**Comment by adrientetar** [comment]
@mikeNG http://permalink.gmane.org/gmane.linux.ports.arm.msm/3063

**Comment by mikeNG** [comment]
@nobodyAtall What do you think about merging this? I updated the defconfigs not to change the default scheduler, just enable it

**Pull request merged**
