### PR TITLE
sii9024a: fixup and enable

### PR DESCRIPTION
**Pull request by adrientetar**

### CODE REVIEW

**Comment by mikeNG** [comment]
The commit message says haida but the defconfig is for hallon?

**Comment by nobodyAtall** [comment]
ec1ba34 is unecessary. Kernel builds fine without it. 
For d3f48f8 the description seems wrong, plus more files are needed for proper support.

**Comment by adrientetar** [comment]
ec1ba34 fixes error that occurs when you have HDMI enabled (sii9024a) which is NOT the case with current haida defconfig
d3f48f8 is my error: haida and hallon are the exact same so I wanted to update haida defconfig, I'll correct that

**Comment by mikeNG** [comment]
@adridu59 wouldn't it be better to ifdef the sii9024a change then?

**Comment by adrientetar** [comment]
@nobodyAtall rebased against latest changes

**Comment by M66B** [comment]
For ec1ba34 I guess you can use:
https://github.com/nobodyAtall/msm7x30-3.0.x-nAa/blob/M7630AABBQMLZA404033I-nAa-master/drivers/video/msm/external_common.c#L80
Needs makefile changes and config.

**Comment by adrientetar** [comment]
@M66B Nice, thanks for the suggestion, I added a select for INTERFACE_COMMON for the sii panel, other panels seem to have HDMI_COMMON selected too but I'll see how this builds without it for now..

EDIT: seems like HDMI common is required too!

EDIT: compiles just fine!

**Comment by M66B** [comment]
@adridu59 please enable HDMI for iyokan too

**Comment by mikeNG** [comment]
Does it work?

**Comment by adrientetar** [comment]
@mikeNG It compiles fine now at least, the last time I compiled a build I got black screen on boot so can't really say if it's my bootenv or whatever... will try in a few mins

**Comment by adrientetar** [comment]
Can't find my HDMI cable... can someone try it?

**Comment by mikeNG** [comment]
Anzu has hdmi too

**Comment by M66B** [comment]
I guess some userland will be necessary, so check first for a second framebuffer in /dev/graphics

**Comment by adrientetar** [comment]
@M66B Can you explain a bit more?
Even if we don't have the libs to make that work on CM, stock ROM is still an option.
@nobodyAtall Why not merge 1af216118013db09bd02265db8ff81f044ea2780?

**Comment by nobodyAtall** [comment]
@adridu59 thanks, merged.

**Pull request closed without merging**
